name: dump log files
runs:
  using: composite
  steps:
    - name: service logs
      continue-on-error: true
      shell: bash
      run: ./logs-and-exit-for service
    - name: postgres logs
      continue-on-error: true
      shell: bash
      run: ./logs-and-exit-for postgres
    - name: postgres-14 logs
      continue-on-error: true
      shell: bash
      run: ./logs-and-exit-for postgres-14
