---
name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./lint
  test-new-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (happy path)
        shell: bash
        run: ./test-new-install --force
      - uses: actions/dump-log-files
  test-happy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (happy path)
        shell: bash
        run: ./test-migration_ok --force
      - uses: actions/dump-log-files
  test-no-space-early:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_no-space-destination --force
      - uses: actions/dump-log-files
  test-no-space-late:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_late-failure --force
      - uses: actions/dump-log-files
  test-docker-build-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_docker-build-failure --force
      - uses: actions/dump-log-files
