name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-the-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./test-tests
  test-migration-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration
        shell: bash
        run: ./test-migration
      - name: postgres logs
        if: always()
        run: docker logs central_postgres_1
      - name: postgres-14 logs
        if: always()
        run: docker logs central_postgres-14_1
  test-migration-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - name: test migration
        shell: bash
        run: ./test-migration
  test-migration-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./install-docker-macos
      - name: test migration
        shell: bash
        run: ./test-migration
  test-migration-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: switch docker to linux mode
        shell: powershell
        run: ./DockerCli.exe -SwitchDaemon .
      - name: test migration
        shell: bash
        run: ./test-migration
