---
name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-the-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./test-tests
  test-migration-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (happy path)
        shell: bash
        run: ./test-migration --force
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_no-space-destination --force
      - name: service logs
        if: always()
        run: ./logs-and-exit-for service
      - name: postgres logs
        if: always()
        run: ./logs-and-exit-for postgres
      - name: postgres-14 logs
        if: always()
        run: ./logs-and-exit-for postgres-14
